### ISSUE TITLE
Not work on Cider V1.6.1

### ISSUE THREAD

**Issue by ChiBei** [yazninja/ivanced#5]
FileError: 'http://localhost:9000/plugins/ivanced/less/cupertinofont.less' wasn't found (404)
in [cupertinofont.less](http://localhost:9000/plugins/ivanced/less/cupertinofont.less)

**Comment by BrayanOfficiel** [comment]
same

**Comment by yazninja** [comment]
Ivanced is deprecated

**Comment by 991547436** [comment]
删除这个文件夹(文件夹不存在时可以尝试查找Plugins目录中包含这个文件的目录ivanced-vue.js)
C:\Users\文件名\AppData\Roaming\Cider\Plugins\gh_475359369

**Comment by yazninja** [comment]
> 删除这个文件夹(文件夹不存在时可以尝试查找Plugins目录中包含这个文件的目录ivanced-vue.js) C:\Users\文件名\AppData\Roaming\Cider\Plugins\gh_475359369

ivanced is deprecated, use iTheme (in Themes) instead
